### ISSUE TITLE
Access denied to user scm

### ISSUE THREAD

**Issue by ramtindavanlou** [ramtindavanlou/Cloudera_bootcamp#11]
Had this access denied issue, even though I granted access to scm user to scm database

```
[root@ip-172-31-7-0 etc]# /usr/share/cmf/schema/scm_prepare_database.sh mysql scm scm
Enter SCM password:
JAVA_HOME=/usr/lib/jvm/jre-openjdk
Verifying that we can write to /etc/cloudera-scm-server
Creating SCM configuration file in /etc/cloudera-scm-server
Executing:  /usr/lib/jvm/jre-openjdk/bin/java -cp /usr/share/java/mysql-connector-java.jar:/usr/share/java/oracle-connector-java.jar:/usr/share/cmf/schema/../lib/* com.cloudera.enterprise.dbutil.DbCommandExecutor /etc/cloudera-scm-server/db.properties com.cloudera.cmf.db.
[                          main] DbCommandExecutor              INFO  Unable to login using supplied username/password.
[                          main] DbCommandExecutor              ERROR Error when connecting to database.
java.sql.SQLException: Access denied for user 'scm'@'localhost' (using password: NO)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:875)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1712)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1228)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)[mysql-connector-java.jar:5.1.39]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[:1.7.0_111]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)[:1.7.0_111]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[:1.7.0_111]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)[:1.7.0_111]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)[mysql-connector-java.jar:5.1.39]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)[mysql-connector-java.jar:5.1.39]
        at java.sql.DriverManager.getConnection(DriverManager.java:571)[:1.7.0_111]
        at java.sql.DriverManager.getConnection(DriverManager.java:215)[:1.7.0_111]
        at com.cloudera.enterprise.dbutil.DbCommandExecutor.testDbConnection(DbCommandExecutor.java:243)[db-common-5.8.2.jar:]
        at com.cloudera.enterprise.dbutil.DbCommandExecutor.main(DbCommandExecutor.java:137)[db-common-5.8.2.jar:]
[                          main] DbCommandExecutor              ERROR Exiting with exit code 8
--> Error 8, giving up (use --force if you wish to ignore the error)
```

**Comment by ramtindavanlou** [comment]
Here's my action plan to fix:

1- create the database again
2- grant all privileges to scm for scm database from the other node
3- re-run the command /scm_prepare_database.sh

**Comment by ramtindavanlou** [comment]
Resolved the problem
